import { StyleSheet } from "@react-pdf/renderer";
import { reportPdfTheme as t } from "./theme";

export const reportPdfStyles = StyleSheet.create({
  page: {
    padding: t.spacing.pagePadding,
    fontFamily: t.fonts.body,
    fontSize: t.typography.bodySize,
    color: t.colors.neutral[900],
  },
  header: {
    marginBottom: t.spacing.headerBottom,
    paddingBottom: t.spacing.blockGap,
    borderBottomWidth: 2,
    borderBottomColor: t.colors.primary,
  },
  title: {
    fontFamily: t.fonts.heading,
    fontSize: t.typography.titleSize,
    fontWeight: 700,
    color: t.colors.primary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: t.typography.subtitleSize,
    color: t.colors.neutral[500],
  },
  section: {
    marginBottom: t.spacing.sectionGap,
  },
  sectionTitle: {
    fontFamily: t.fonts.heading,
    fontSize: t.typography.sectionTitleSize,
    fontWeight: 700,
    color: t.colors.neutral[900],
    marginBottom: t.spacing.blockGap,
    paddingLeft: 8,
    borderLeftWidth: 3,
    borderLeftColor: t.colors.secondary,
  },
  kpiRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: t.spacing.blockGap,
    marginBottom: t.spacing.sectionGap,
  },
  kpiCard: {
    flexGrow: 1,
    minWidth: "30%",
    padding: t.spacing.cardPadding,
    backgroundColor: t.colors.neutral[50],
    borderRadius: t.radii.card,
    borderWidth: 1,
    borderColor: t.colors.border,
  },
  kpiLabel: {
    fontSize: t.typography.kpiLabelSize,
    color: t.colors.neutral[500],
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  kpiValue: {
    fontFamily: t.fonts.heading,
    fontSize: t.typography.kpiValueSize,
    fontWeight: 700,
    color: t.colors.primary,
  },
  kpiValueSecondary: {
    fontFamily: t.fonts.heading,
    fontSize: t.typography.kpiValueSize,
    fontWeight: 700,
    color: t.colors.secondary,
  },
  kpiValueAccent: {
    fontFamily: t.fonts.heading,
    fontSize: t.typography.kpiValueSize,
    fontWeight: 700,
    color: t.colors.accent,
  },
  table: {
    width: "100%",
    marginBottom: t.spacing.blockGap,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: t.colors.border,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  tableRowHeader: {
    flexDirection: "row",
    backgroundColor: t.colors.neutral[100],
    borderBottomWidth: 2,
    borderBottomColor: t.colors.borderStrong,
    paddingVertical: 8,
    paddingHorizontal: 4,
    fontFamily: t.fonts.heading,
    fontWeight: 700,
    fontSize: t.typography.smallSize,
  },
  tableCell: {
    flex: 1,
    fontSize: t.typography.bodySize,
  },
  tableCellRight: {
    flex: 1,
    fontSize: t.typography.bodySize,
    textAlign: "right",
  },
  footer: {
    position: "absolute",
    bottom: t.spacing.pagePadding,
    left: t.spacing.pagePadding,
    right: t.spacing.pagePadding,
    paddingTop: t.spacing.footerTop,
    borderTopWidth: 1,
    borderTopColor: t.colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: t.typography.smallSize,
    color: t.colors.neutral[500],
  },
  chartImage: {
    width: "100%",
    height: 200,
    objectFit: "contain",
    marginBottom: t.spacing.blockGap,
    borderRadius: t.radii.small,
  },
  barChartBar: {
    height: 20,
    borderRadius: 2,
    marginBottom: 6,
  },
  emptyState: {
    padding: t.spacing.sectionGap,
    textAlign: "center",
    color: t.colors.neutral[500],
    fontSize: t.typography.bodySize,
  },
});
